name: golang

on:
  push:
    branches: 
    - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: "gh-pages"
        path: "gh-pages"
    - uses: actions/checkout@v2
      with:
        path: "main"
    - name: install-docpress
      run: |
        npm install docpress
        npm install markdown-it-emoji
    - name: generate-site
      run: |
        cd main
        ../node_modules/docpress/bin/docpress b
        ls -l _docpress
    - name: clean-branch
      run: |
        cd gh-pages
        git rm ./*
    - name: update-branche
      run: |
        cp -r main/_docpress/* gh-pages/
        cd gh-pages
        git config --global user.name 'github action'
        git config --global user.email '48486938+dergeberl@users.noreply.github.com'
        git add .
        git commit -m "update docs"
        git push
