name: golang

on:
  push:
    branches: 
    - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: "gh-pages"
        path: "gh-pages"
    - uses: actions/checkout@v2
      with:
        path: "main"
    - run: |
        npm install docpress
        npm install markdown-it-emoji
    - run: |
        cd main
        ../node_modules/docpress/bin/docpress b
        ls -l _docpress
    - run: |
        cd gh-pages
        git rm ./*
    - run: |
        cp main/_docpress/* gh-pages/
        cd gh-pages
        git add .
        git commit -m "update docs"
        git push
